### PR TITLE
Windows 10 fixes

### PR DESCRIPTION
**Pull request by Lootyhoof**
Follow-up to #34 

Turns out I forgot to remove a few lines. Go figure.

### CODE REVIEW

**Comment by wolfbeast** [comment]
Tag #31

**Comment by wolfbeast** [comment]
This takes care of the tab titles, but unfortunately not of the "open new tab" and "close X" controls, yet.

**Comment by Lootyhoof** [comment]
Works for me..?

Win10

All I did was take the current styling and remove the lines in this PR.

**Comment by wolfbeast** [comment]
Ah.. wait, it does, but it doesn't refresh the UI. hmm...

**Comment by Lootyhoof** [comment]
It's based on `brighttext`, like it is in upstream Firefox.

**Comment by wolfbeast** [comment]
It seems particularly an issue when the color is changed while the window has focus (e.g. slideshow background image + color based on image). I'm guessing "brighttext" isn't updated or doesn't trigger a repaint in that case, or the property lags behind and misses the repraint triggered in syscolorupdate.
image1

**Comment by Lootyhoof** [comment]
It isn't, unfortunately - it's residing in `browser.js` in code that only re-verifies when a `lwtheme` is applied or the window is made inactive. I recall this being an issue when we implemented this on the Pale Moon side also, though even then we weren't sure how best to work around this.

**Comment by wolfbeast** [comment]
I looked into the code and there isn't really a way around this if relying on the brighttext property, unless we put its refresh on a timer, but that'd become rather expensive, I think. I'll have to investigate if it's possible to use an observer of some sort, otherwise it'll have to be done with media queries (since those do get refreshed properly).

**Pull request merged**
