### PR TITLE
Restore the Toolkit Error Console

### LINKED ISSUE #246: Restore the Toolkit Error Console
The Toolkit Error Console aka the old jsconsole is important for platform development as it is an application independent component.

I am planning to effectively revert https://github.com/mozilla/gecko-dev/commit/1adf4b4140ec74eda31a8e137ba515c0ddefda57 (Mozilla Bug 1278368)

### PR DESCRIPTION
**Pull request by mattatobin**
This pull request is pending @trav90 for Linux verification.. Meanwhile I am filing a review..

----

Resolves #246

### CODE REVIEW

**Comment by trav90** [comment]
I am not currently near my build machine. As soon as I get home I will fire off a build and report back here once it is complete.

**Comment by trav90** [comment]
Compiling now. Will report back shortly.

**Comment by mattatobin** [comment]
Understood.. Will fix.

**Comment by mattatobin** [comment]
There that should be it..

**Pull request merged**
