### PR TITLE
Make it possible to add cookies, local and session storage entries

### LINKED ISSUE #338: DevTools - storage - make it possible to add cookies, local and session storage entries
The context menu / the button - it should provide an option to add cookies, local and session storage entries.

### PR DESCRIPTION
**Pull request by janekptacijarabaci**
This resolves #338 → You add the label `Devtools`, please

Bug(s):
https://bugzilla.mozilla.org/show_bug.cgi?id=1231452
https://bugzilla.mozilla.org/show_bug.cgi?id=1363006

Ad [onAddItem - if (this.tree.selectedItem)](https://github.com/MoonchildProductions/moebius/pull/339/files#diff-ae1271e0a4cb04b6b6756d02b117e260R1120):
https://bugzilla.mozilla.org/show_bug.cgi?id=1433844

---

You add the label `Theme changes`, please.

---

I've created the new build (x32, Windows) and tested.

### CODE REVIEW

**Comment by mattatobin** [comment]
Why?

**Comment by janekptacijarabaci** [comment]
I think the user/developer should have as much freedom as possible.

**Comment by mattatobin** [comment]
Ok, but why is this feature needed? Simply because Firefox has it? I am confused on the justification.

**Comment by janekptacijarabaci** [comment]
No, because it can be useful... Just like any of the devtools.
I have no other answer.

**Comment by wolfbeast** [comment]
@mattatobin labels should go primarily on issues, not PRs.

**Pull request merged**
