### PR TITLE
The Performance Resource Timing (improvements)

### PR DESCRIPTION
**Pull request by janekptacijarabaci**
Ad #158

See:
https://bugzilla.mozilla.org/show_bug.cgi?id=1393837
https://bugzilla.mozilla.org/show_bug.cgi?id=1263722
https://bugzilla.mozilla.org/show_bug.cgi?id=1403154
https://bugzilla.mozilla.org/show_bug.cgi?id=1403926
https://bugzilla.mozilla.org/show_bug.cgi?id=1377251

__An example (for Scratchpad):__

Go to: http://json-schema.org/examples.html

``` javascript
function print_start_and_end_properties(perfEntry, num) {
  properties = ["connectStart", "connectEnd",
                "domainLookupStart", "domainLookupEnd",
                "fetchStart", 
                "redirectStart", "redirectEnd",
                "requestStart", 
                "responseStart", "responseEnd",
                "secureConnectionStart",
		"workerStart"];

  for (var i=0; i < properties.length; i++) {
    var supported = properties[i] in perfEntry;
    if (supported) {
      var value = perfEntry[properties[i]];
      console.log("...[" + num + "] " + properties[i] + " = " + value);
    } else {
      console.log("...[" + num + "] " + properties[i] + " = NOT supported");
    }
  }
}

var xmlhttp = new XMLHttpRequest();
xmlhttp.open("get", "http://json-schema.org/example/geo.json", true);
xmlhttp.onload = function () {
  var p = performance.getEntriesByType("resource");
  for (var i=0; i < p.length; i++) {
    print_start_and_end_properties(p[i], i);
  }
};
xmlhttp.send();
```

---

I've created the new build (x32, Windows) and tested.

### CODE REVIEW

**Comment by mattatobin** [comment]
This is a lot of changes.. What are the implications and side effects?

**Comment by janekptacijarabaci** [comment]
Mainly:
Make the PerformanceNavigationTiming timestamps be relative to startTime (and correct)
(the PerformanceNavigationTiming entry should only be available after the page is fully loaded)
- https://bugzilla.mozilla.org/show_bug.cgi?id=1403926#c0
- https://bugzilla.mozilla.org/show_bug.cgi?id=1263722#c0

**Comment by mattatobin** [comment]
Does this have any effects for Add-ons that monitor such things?

**Comment by janekptacijarabaci** [comment]
I'm sorry, but I have no other answer except for what I told you. I do not expect addons corruption, but I can not rule it out either.

> their goals may not be our goals

It's the same as with other PRs. It's relevant information that solves the problems. for me. If it is not useful for you and your project, you can skip it.
e.g. I have no doubt about the usefulness of this PR: #142 (even if there are other options), but it was rejected.

**Comment by mattatobin** [comment]
Please don't misunderstand me.. I am not criticizing your work and am appreciative of all the stuff you have done thus far. I just want to know more and would be more appreciative of more detailed info and for factors like add-ons to be kept in mind.

If a change in behavior could impact add-ons so be it.. Just would be nice to know. I am not sure if this will have any such effect .. I doubt it except in some extreme edge case or whatever.. It's fine.

**Comment by janekptacijarabaci** [comment]
e.g. the difference between relative and absolute timestamps (or in general Performance API)... I don't know any such addon who uses it.

**Pull request merged**
