### PR TITLE
Optimize operations on root of deeply-nested frame tree

### PR DESCRIPTION
**Pull request by janekptacijarabaci**
__An example - but it is individual:__

---
__testcase 1__
(https://bugzilla.mozilla.org/attachment.cgi?id=8843501)

\- actual results:
  \> 2000 ms

\- expected results:
  \< 100 ms

---
__testcase 2__
(https://bugzilla.mozilla.org/attachment.cgi?id=8843503)

\- actual results:
  \> 3000 ms

\- expected results:
  \< 2000 ms

---
__testcase 3__
(https://bugzilla.mozilla.org/attachment.cgi?id=8843521)

\- actual results:
  \> 3000 ms

\- expected results:
  \< 2000 ms

See:
https://bugzilla.mozilla.org/show_bug.cgi?id=1361268
https://bugzilla.mozilla.org/show_bug.cgi?id=1344398
https://bugzilla.mozilla.org/show_bug.cgi?id=1364180
https://bugzilla.mozilla.org/show_bug.cgi?id=1367568

---

I've created the new build (x32, Windows) and tested.

### CODE REVIEW

**Comment by wolfbeast** [comment]
Probably something this might be worth porting to our Pale Moon repo.

**Comment by janekptacijarabaci** [comment]
Adjustments would have to be made. I leave it to someone else.

**Comment by wolfbeast** [comment]
Well, d'uh. of course adjustments would have to be made. I did say "porting", not "applying",'grafting" or other terms that might indicate it would apply as-is.
Can you at least indicate if it would generally be portable with adjustments or not?

**Comment by janekptacijarabaci** [comment]
I'm sorry, but I do not know. Quite often: some changes look simple but they are not (in real implementation).

**Pull request merged**
